import React from 'react'
import MyProfile from './my-profile'
import LayoutClient from '../../components/LayoutClient'

export const metadata = {
    title: 'Mi Perfil',
    description: 'Generated by create next app',
  }

const Page = () => {
  return (
    <LayoutClient>
        <main className='contenedor'>
        <MyProfile />
        </main>
    </LayoutClient>
    
  )
}

export default Page