import React from "react";
import MyLodging from "./my-lodging";

export const metadata = {
  title: 'Mi Hospedaje',
  description: 'Generated by create next app',
}

const Page = () => {
  return <MyLodging />;
};

export default Page;
