import React from "react";
import NoSubscribe from "./no-subscribe";
import LayoutClient from "../../components/LayoutClient";

export const metadata = {
  title: 'Bienvenido',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <LayoutClient>
      <main className="contenedor">
        <NoSubscribe />
      </main>
    </LayoutClient>
  );
};

export default Page;
