import React from 'react'
import Verify from './verify'

export const metadata = {
  title: 'verificando',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <Verify/>
  )
}

export default Page