import React from 'react'
import SetDatas from './set-datas'
import LayoutRegister from '../Layout';

export const metadata = {
  title: 'Add Datas',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <LayoutRegister>
      <SetDatas />
    </LayoutRegister>
  )
}
export default Page;