import React from 'react'
import NewAccount from './new-account';

export const metadata = {
  title: 'Verificar',
  description: 'Generated by create next app',
}
const Page = () => {
  return (
    <NewAccount />
  )
}

export default Page;