import React from 'react'
import LayoutClient from '../../components/LayoutClient'
import AddLodgingEstandar from './add-lodging-estandar'

export const metadata = {
  title: 'Agregar Hospedaje',
  description: 'Generated by create next app',
}


export const Page = () => {
  return (
    <LayoutClient>
        <main className='contenedor'>
            <AddLodgingEstandar />
        </main>
    </LayoutClient>
  )
}
export default Page;
