import React from 'react'
import Dashboard from './content-manager'

export const metadata = {
  title: 'Bienvenido',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <Dashboard />
  )
}

export default Page