import React from 'react'
import LayoutClient from '../../components/LayoutClient'
import MyLodgingEstandar from './my-lodging-estandar'

export const metadata = {
  title: 'Mi hospedaje',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <LayoutClient>
        <main className='contenedor'>
            <MyLodgingEstandar />
        </main>
    </LayoutClient>
  )
}

export default Page