import React from 'react'
import AddLodging from './add-lodging'
import LayoutClient from '../../components/LayoutClient'

export const metadata = {
  title: 'Agregar Hospedaje',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <LayoutClient>
      <main className='contenedor'>
      <AddLodging />
      </main>
    </LayoutClient>
  )
}

export default Page