import React from 'react'
import AddLodging from './add-lodging'

export const metadata = {
  title: 'Agregar Hospedaje',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <AddLodging />
  )
}

export default Page