import React from "react";
import SetEmail from "./verify-email";
import LayoutRegister from "../Layout";

export const metadata = {
  title: 'Add Email',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <LayoutRegister>
      <SetEmail />
    </LayoutRegister>
  );
};

export default Page;
